config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  namespace :api do
    namespace :v1 do
      resources :users, only: [] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
  devise_for :users
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    if user.role == 'admin'
      can :manage, :all
    else
      can :read, :all
      can :create, Post, author_id: user.id
      can :create, Comment, author_id: user.id
      can :create, Like
      can :destroy, Post do |post|
        post.author_id == user.id
      end
      can :destroy, Comment do |comment|
        comment.author_id == user.id
      end
    end

    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, foreign_key: 'author_id', class_name: 'User'
  belongs_to :post

  after_create :update_post_comments_counter

  validates :text, presence: true

  private

  def update_post_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_post_likes_counter

  private

  def update_post_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_create :update_author_posts_counter

  validates :title, presence: true, allow_blank: false, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, allow_nil: true },
                               comparison: { greater_than_or_equal_to: 0, allow_nil: true }
  validates :likes_counter, numericality: { only_integer: true, allow_nil: true },
                            comparison: { greater_than_or_equal_to: 0, allow_nil: true }

  def update_author_posts_counter
    author.update_posts_counter
  end

  def update_comments_counter
    update(comments_counter: comments.count)
  end

  def update_likes_counter
    update(likes_counter: likes.count)
  end

  def recent_comments
    comments.order(created_at: :desc).includes([:author]).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id

  validates :name, presence: true, allow_blank: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }

  before_save :generate_api_token

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def update_posts_counter
    update(posts_counter: posts.count)
  end

  def update_comments_counter
    update(comments_counter: comments.count)
  end

  private

  def generate_api_token
    self.api_token = SecureRandom.hex(16)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create], if: -> { request.format.json? }

  def index
    user = User.find(params['user_id'])
    post = user.posts.find(params['post_id'])
    comments = post.comments
    render json: comments
  end

  def create
    token = request.headers['X-Token']
    user = User.find_by(api_token: token)
    post = Post.find(params['post_id'])

    new_comment = post.comments.new(
      text: params['text'],
      user:
    )

    new_comment.save
    render json: { success: 'Comment added successfully' }
  rescue StandardError => e
    render json: { error: e.message }
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    posts = User.find(params['user_id']).posts

    render json: posts
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]
  load_and_authorize_resource
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @post = Post.find(params[:post_id])
    @comment.author_id = current_user.id
    @comment.post_id = @post.id

    if @comment.save
      redirect_to user_post_path(user_id: @post.author_id, id: @post.id), notice: 'comment created succesfully'
    else
      render :new, alert: 'Error occured'
    end
  end

  def comment_params
    params.require(:comment).permit(:text)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    @post.decrement!(:comments_counter)
    @comment.destroy!
    redirect_to user_post_path(id: @post.id), notice: 'Comment was successfully deleted!'
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.new(author_id: current_user.id, post_id: @post)
    if @like.save
      redirect_to user_post_path(user_id: @post.author_id, id: @post.id)
    else
      render :new, notice: 'You are not able to like the post'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments, :likes)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to user_path(id: @post.author_id), notice: 'Post was successfully created.'
    else
      flash.now[:alert] = 'An error has occurred while creating the post.'
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @author = @post.author
    @author.decrement!(:posts_counter)
    @post.destroy!
    redirect_to user_posts_path(id: @author.id), notice: 'Post was deleted successfully!'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.includes(:posts).find(params[:id])
  end
end

app/helpers/api/v1/comments_helper.rb
module Api::V1::CommentsHelper
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/user_posts_helper.rb
module UserPostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<main>
  <h1>Add a new comment</h1>
  <%= form_with model: @comment, url: user_post_comments_path, class: "form" do |form| %>
    <%= form.label :text %> <br>
    <%= form.text_area :text , cols: 30, rows: 10 %> <br>
    <%= form.submit "Submit", class: "btn" %>
  <% end %>
</main>

app/views/likes/new.html.erb
<h1>Likes#new</h1>
<p>Find me in app/views/likes/new.html.erb</p>

app/views/posts/index.html.erb
<main>
  <section>
    <div class="card">
      <div class="user-image border"></div>
      <div class="user-data border">
        <h1><%= @user.name %></h1>
        <p class="number-posts"><%= @user.posts_counter %> Posts</p>
        <div class="right">
        <% if current_user %>
        <%= link_to "Add a post",new_user_post_path(@user), method: :get, class: "btn right" %>
      <% end %>
        </div>
      </div>
    </div>
  </section>
  <section>
    <ul>
      <% @posts.each do |post| %>
        <%= link_to user_post_path(user_id: post.author_id, id: post.id) do %>
          <li class="card hover">
            <div class="card">
              <h2><%= post.title %></h2>
              <p><%= post.text %></p>
              <div class="right">
                <span>Comments: <%= post.comments_counter %></span>
                <span>Likes: <%= post.likes_counter %> </span>
              </div>
            </div>
            <div class="commets-container">
              <h4>Comments:</h4>
              <ul>
                <% post.recent_comments.each do |comment| %>
                  <p><%= comment.author.name %>: <%= comment.text %></p>
                <% end %>
              </ul>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  </section>
  <%= link_to "Pagination", user_posts_path(user_id: @user.id), class: "btn pagination" %> 
</main>

app/views/posts/new.html.erb
<main>
  <h1>Add a new post</h1>
  <%= form_with model: @post, url: user_posts_path, class: "form" do |form| %>
    <%= form.label :title %> <br>
    <%= form.text_field :title %> <br>
    <%= form.label :text %> <br>
    <%= form.text_area :text , cols: 30, rows: 10 %> <br>
    <%= form.submit "Submit", class: "btn" %>
  <% end %>
</main>

app/views/posts/show.html.erb
<main>
  <section class="card column">
    <div class="card column">
      <h2><%= @post.title %></h2>
      <p><%= @post.text %></p>
      <div class="right">
        <span>Comments: <%= @post.comments_counter %></span>
        <span>Likes: <%= @post.likes_counter %> </span>
      </div>
      <div class="button_field">
      <% if user_signed_in? %>
        <%= link_to "Comment", new_user_post_comment_path(user_id: @post.author_id, post_id: @post.id ), class: "btn" %>
        <%= form_with model: @like, url: user_post_likes_path(post_id: @post.id) do |form| %>
          <%= form.submit "Like", class: "btn" %>
        <% end %>
        <% if can? :destroy, @post %>
          <%= button_to "Delete post", user_post_path(user_id: @post.author.id, post_id: @post.id), method: :delete, class: "btn"  %>
        <% end %>
      <% end %>
      </div>
    </div>
    <div class="commets-container">
      <h4>Comments:</h4>
      <ul>
        <% @post.comments.includes(:author).includes(:post).each do |comment| %>
        <li>
          <p><%= comment.author.name %>: <%= comment.text %></p>
          <% if can? :destroy, comment %>
            <%= button_to "Delete", user_post_comment_path(user_id: comment.author.id, post_id: comment.post.id, id: comment.id), method: :delete, class: "btn"  %>
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>
  </section>
</main>

app/views/users/index.html.erb
<main>
  <section>
    <ul>
    <% @users.each do |user| %>
      <%= link_to user_path(user) do %>
        <li class="card hover">
          <% if user.photo.present? %>
            <%= image_tag(user.photo, class: "user-image border") %>
          <% else %> 
            <%= image_tag("https://picsum.photos/200", class: "user-image border") %>
          <% end %>
          <div class="user-data border">
            <h1><%= user.name %></h1>
            <p class="number-posts"><%= user.posts_counter %> Posts</p>
            <!-- Other user data and content -->
          </div>
        </li>
      <% end %>
    <% end %>
    </ul>  
  </section>
</main>

app/views/users/show.html.erb
<main>
  <section>
    <div class="card">
    <% if @user.photo.present? %>
    <%= image_tag(@user.photo, class: "user-image border") %>
  <% else %>
    <!-- Provide a placeholder image or default image here if 'user.photo' is nil -->
  <% end %>
        <div class="user-data border">
        <h1><%= @user.name %></h1>
        <p class="number-posts"><%= @user.posts_counter %> Posts</p>
    </div>
    <div class="card">
      <div class="column">
        <h3>Bio:</h3>
        <p><%= @user.bio %></p>
      </div>
    </div>
  </section>
  <section class="center">
    <ul>
      <% @user.posts.each do |post| %>
        <%= link_to user_post_path(@user, post) do %>
          <li class="card column hover">
            <h3 class="left"><%= post.title %></h3>
            <h4 class="left"><%= post.text %></h4>
            <div class="right">
              <span>Comments: <%= post.comments_counter %></span>
              <span class="left">Likes: <%= post.likes_counter %></span>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
    <%= link_to "See all posts", user_posts_path(user_id: @user.id), class: "btn" %>
  </section> 
</main>